name: Colours Stained Glass
favicon: null
layout_spectrum: 0.958119377726689
typography_spectrum: 0.8670705349650234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4532813122496009
  lightness: 0.8334589705336839
  saturation: 0.2339324178174138
  rhythmicContrast: 0.7570653986185789
purpose: []
